# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afaaaa73eeb66e5100b66a4f71620e437d4ed9b0eff2449a80f895fdf18f01a046c78ad226281afcb029375d9653c0bb951fd1b46ff83fd0ee9a308162a5fa93

test:
  secret_key_base: fb76caf8113eb7c61c721752ce7b3674fb0906451625d2f4b17a8b15f7080f344b7db5029069980d65bd5a964405bfc84fe9e3d5d732ae0290b83a867732780f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
